### ISSUE TITLE
@foreach not working - @for being used

### ISSUE THREAD

**Issue by saulposel** [Corviz/crow#2]
Hey,

It appears that using @foreach causes an error, as seemingly the library is trying to utilise the @for method for some reason.

In debugging, I have check the regular expression used in the CodeConverter::convertMethods class method, but am unsure how @for is being matched in error, as the regex seems correct.

I tested by 
a) removing the 'for' and 'endfor' items, 
and b) moving the 'for' and 'endfor' items to after the 'foreach' and 'endforeach' items
in the Crow::DEFAULT_METHODS array, and that fixed the error.

Not sure, but I hope that helps track down the issue?

Thanks for all the hard work!

If I can be of any help, I will do my best.

**Comment by carloscarucce** [comment]
Thanks for your report. The problem was that **@for** and **@foreach** starts with the same characters sequence.
I've made a change that the interpreter now differs one from another according to the tag length, avoiding this and probably some related future issues.
